version: '3'

services:
  dev:
    image: node:16
    container_name: lru-ttl-cache
    user: 'node:node'
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - 3000:3000